###
#
# docker run -i --rm -p 8080:8080 quarkus/using-vertx
#
###
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.2
RUN microdnf --enablerepo=*debug* install gdb glibc-debuginfo zlib-debuginfo
WORKDIR /work/
COPY target/*-runner /work/application
COPY target/*-runner.debug /work/
COPY target/quarkus-native-image-source-jar/sources /work/sources
RUN chmod 775 /work
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
