FROM registry.access.redhat.com/ubi8/ubi-minimal:8.7
RUN microdnf --enablerepo=ubi-8-baseos-debug-rpms --enablerepo=ubi-8-appstream-debug-rpms install gdb zlib-debuginfo glibc-debuginfo
WORKDIR /work/
COPY target/quarkus-runner /work/application
COPY target/quarkus-runner.debug /work/application.debug
COPY target/sources /work/sources
RUN chmod 775 /work -R
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
