quarkus.log.level=SEVERE
quarkus.banner.enabled=false
# CycloneDX SBOM embedding config
quarkus.cyclonedx.enabled=true
quarkus.cyclonedx.embedded.enabled=true
quarkus.cyclonedx.embedded.compress=false
quarkus.cyclonedx.pretty-print=true
