FROM registry.access.redhat.com/ubi10/ubi-minimal:10.1
WORKDIR /work/
COPY target/*-runner /work/application
COPY jfr-perf.jfc /work/jfr-perf.jfc
RUN chmod 775 /work -R
EXPOSE 8080
ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
